// Sample data for the JK2 CTF Tournament with custom player names

// Teams data
export const teams = [
  {
    id: 1,
    name: "93 Octane",
    founded: "2023",
    players: ["bizzle", "fetchd", "shax", "andrew", "interlude", "loom", "ultra"],
    stats: {
      matchesPlayed: 8,
      matchesWon: 6,
      matchesDrawn: 1,
      matchesLost: 1,
      captures: 32,
      flagReturns: 28,
      kills: 245,
      points: 19,
    },
  },
  {
    id: 2,
    name: "Crash squad",
    founded: "2023",
    players: ["cooky", "arhont", "dreamwise", "cheese", "original", "phoenix", "jin"],
    stats: {
      matchesPlayed: 8,
      matchesWon: 5,
      matchesDrawn: 2,
      matchesLost: 1,
      captures: 29,
      flagReturns: 31,
      kills: 267,
      points: 17,
    },
  },
  {
    id: 3,
    name: "rTr",
    founded: "2023",
    players: ["suvix", "millhouse", "xan", "phenom", "plasma", "flawless", "levi"],
    stats: {
      matchesPlayed: 8,
      matchesWon: 4,
      matchesDrawn: 1,
      matchesLost: 3,
      captures: 24,
      flagReturns: 22,
      kills: 198,
      points: 13,
    },
  },
  {
    id: 4,
    name: "Batchers",
    founded: "2023",
    players: ["eze", "luke", "downfall", "dogsage", "giraffe", "Ferox", "killzo"],
    stats: {
      matchesPlayed: 8,
      matchesWon: 3,
      matchesDrawn: 2,
      matchesLost: 3,
      captures: 21,
      flagReturns: 19,
      kills: 176,
      points: 11,
    },
  },
  {
    id: 5,
    name: "d2dm",
    founded: "2023",
    players: ["goose", "ewok", "Barney", "yuki", "devy", "omerta", "vee"],
    stats: {
      matchesPlayed: 8,
      matchesWon: 2,
      matchesDrawn: 1,
      matchesLost: 5,
      captures: 18,
      flagReturns: 16,
      kills: 154,
      points: 7,
    },
  },
  {
    id: 6,
    name: "szok",
    founded: "2023",
    players: ["sora", "spacedghost", "andon", "matt", "savior", "apple", "amor", "bucky"],
    stats: {
      matchesPlayed: 8,
      matchesWon: 1,
      matchesDrawn: 1,
      matchesLost: 6,
      captures: 14,
      flagReturns: 12,
      kills: 132,
      points: 4,
    },
  },
]

// Players data
export const players = [
  // Force Unleashed
  {
    id: 1,
    name: "bizzle",
    team: "93 Octane",
    team_id: 1,
    role: "Captain",
    stats: {
      impact: 92,
      flagCaptures: 12,
      flagReturns: 10,
      bcKills: 15,
      dbsKills: 8,
      dfaKills: 5,
      overallKills: 78,
      overallDeaths: 32,
      flagholdTime: 345,
      nemesisId: 8,
    },
  },
  {
    id: 2,
    name: "fetchd",
    team: "93 Octane",
    team_id: 1,
    stats: {
      impact: 88,
      flagCaptures: 8,
      flagReturns: 12,
      bcKills: 12,
      dbsKills: 10,
      dfaKills: 3,
      overallKills: 65,
      overallDeaths: 28,
      flagholdTime: 278,
      nemesisId: 9,
    },
  },
  {
    id: 3,
    name: "shax",
    team: "93 Octane",
    team_id: 1,
    stats: {
      impact: 75,
      flagCaptures: 6,
      flagReturns: 4,
      bcKills: 8,
      dbsKills: 6,
      dfaKills: 2,
      overallKills: 42,
      overallDeaths: 35,
      flagholdTime: 198,
      nemesisId: 10,
    },
  },
  {
    id: 4,
    name: "andrew",
    team: "93 Octane",
    team_id: 1,
    stats: {
      impact: 70,
      flagCaptures: 4,
      flagReturns: 2,
      bcKills: 10,
      dbsKills: 4,
      dfaKills: 6,
      overallKills: 38,
      overallDeaths: 30,
      flagholdTime: 156,
      nemesisId: 11,
    },
  },
  {
    id: 5,
    name: "interlude",
    team: "93 Octane",
    team_id: 1,
    stats: {
      impact: 58,
      flagCaptures: 2,
      flagReturns: 0,
      bcKills: 5,
      dbsKills: 2,
      dfaKills: 1,
      overallKills: 22,
      overallDeaths: 18,
      flagholdTime: 87,
      nemesisId: 12,
    },
  },
  {
    id: 6,
    name: "loom",
    team: "93 Octane",
    team_id: 1,
    stats: {
      impact: 40,
      flagCaptures: 0,
      flagReturns: 0,
      bcKills: 0,
      dbsKills: 0,
      dfaKills: 0,
      overallKills: 0,
      overallDeaths: 0,
      flagholdTime: 0,
      nemesisId: 13,
    },
  },
  {
    id: 7,
    name: "ultra",
    team: "93 Octane",
    team_id: 1,
    stats: {
      impact: 40,
      flagCaptures: 0,
      flagReturns: 0,
      bcKills: 0,
      dbsKills: 0,
      dfaKills: 0,
      overallKills: 0,
      overallDeaths: 0,
      flagholdTime: 0,
      nemesisId: 14,
    },
  },
  // Kyber Knights
  {
    id: 8,
    name: "cooky",
    team: "Crash squad",
    team_id: 2,
    role: "Captain",
    stats: {
      impact: 90,
      flagCaptures: 10,
      flagReturns: 8,
      bcKills: 18,
      dbsKills: 12,
      dfaKills: 7,
      overallKills: 85,
      overallDeaths: 30,
      flagholdTime: 320,
      nemesisId: 1,
    },
  },
  {
    id: 9,
    name: "arhont",
    team: "Crash squad",
    team_id: 2,
    stats: {
      impact: 87,
      flagCaptures: 9,
      flagReturns: 11,
      bcKills: 14,
      dbsKills: 9,
      dfaKills: 8,
      overallKills: 72,
      overallDeaths: 35,
      flagholdTime: 290,
      nemesisId: 2,
    },
  },
  {
    id: 10,
    name: "dreamwise",
    team: "Crash squad",
    team_id: 2,
    stats: {
      impact: 76,
      flagCaptures: 5,
      flagReturns: 7,
      bcKills: 10,
      dbsKills: 5,
      dfaKills: 4,
      overallKills: 48,
      overallDeaths: 32,
      flagholdTime: 210,
      nemesisId: 3,
    },
  },
  {
    id: 11,
    name: "cheese",
    team: "Crash squad",
    team_id: 2,
    stats: {
      impact: 68,
      flagCaptures: 3,
      flagReturns: 4,
      bcKills: 8,
      dbsKills: 3,
      dfaKills: 2,
      overallKills: 36,
      overallDeaths: 28,
      flagholdTime: 145,
      nemesisId: 4,
    },
  },
  {
    id: 12,
    name: "original",
    team: "Crash squad",
    team_id: 2,
    stats: {
      impact: 60,
      flagCaptures: 2,
      flagReturns: 1,
      bcKills: 6,
      dbsKills: 2,
      dfaKills: 1,
      overallKills: 26,
      overallDeaths: 22,
      flagholdTime: 98,
      nemesisId: 5,
    },
  },
  {
    id: 13,
    name: "phoenix",
    team: "Crash squad",
    team_id: 2,
    stats: {
      impact: 40,
      flagCaptures: 0,
      flagReturns: 0,
      bcKills: 0,
      dbsKills: 0,
      dfaKills: 0,
      overallKills: 0,
      overallDeaths: 0,
      flagholdTime: 0,
      nemesisId: 6,
    },
  },
  {
    id: 14,
    name: "jin",
    team: "Crash squad",
    team_id: 2,
    stats: {
      impact: 40,
      flagCaptures: 0,
      flagReturns: 0,
      bcKills: 0,
      dbsKills: 0,
      dfaKills: 0,
      overallKills: 0,
      overallDeaths: 0,
      flagholdTime: 0,
      nemesisId: 7,
    },
  },
  // Beskar Battalion
  {
    id: 15,
    name: "suvix",
    team: "rTr",
    team_id: 3,
    role: "Captain",
    stats: {
      impact: 85,
      flagCaptures: 9,
      flagReturns: 7,
      bcKills: 16,
      dbsKills: 7,
      dfaKills: 4,
      overallKills: 68,
      overallDeaths: 34,
      flagholdTime: 280,
      nemesisId: 22,
    },
  },
  {
    id: 16,
    name: "millhouse",
    team: "rTr",
    team_id: 3,
    stats: {
      impact: 78,
      flagCaptures: 6,
      flagReturns: 5,
      bcKills: 12,
      dbsKills: 5,
      dfaKills: 3,
      overallKills: 52,
      overallDeaths: 30,
      flagholdTime: 215,
      nemesisId: 23,
    },
  },
  {
    id: 17,
    name: "xan",
    team: "rTr",
    team_id: 3,
    stats: {
      impact: 72,
      flagCaptures: 4,
      flagReturns: 6,
      bcKills: 9,
      dbsKills: 4,
      dfaKills: 2,
      overallKills: 38,
      overallDeaths: 28,
      flagholdTime: 175,
      nemesisId: 24,
    },
  },
  {
    id: 18,
    name: "phenom",
    team: "rTr",
    team_id: 3,
    stats: {
      impact: 63,
      flagCaptures: 3,
      flagReturns: 2,
      bcKills: 7,
      dbsKills: 3,
      dfaKills: 1,
      overallKills: 24,
      overallDeaths: 22,
      flagholdTime: 120,
      nemesisId: 25,
    },
  },
  {
    id: 19,
    name: "plasma",
    team: "rTr",
    team_id: 3,
    stats: {
      impact: 55,
      flagCaptures: 2,
      flagReturns: 2,
      bcKills: 5,
      dbsKills: 2,
      dfaKills: 1,
      overallKills: 16,
      overallDeaths: 18,
      flagholdTime: 85,
      nemesisId: 26,
    },
  },
  {
    id: 20,
    name: "flawless",
    team: "rTr",
    team_id: 3,
    stats: {
      impact: 40,
      flagCaptures: 0,
      flagReturns: 0,
      bcKills: 0,
      dbsKills: 0,
      dfaKills: 0,
      overallKills: 0,
      overallDeaths: 0,
      flagholdTime: 0,
      nemesisId: 27,
    },
  },
  {
    id: 21,
    name: "levi",
    team: "rTr",
    team_id: 3,
    stats: {
      impact: 40,
      flagCaptures: 0,
      flagReturns: 0,
      bcKills: 0,
      dbsKills: 0,
      dfaKills: 0,
      overallKills: 0,
      overallDeaths: 0,
      flagholdTime: 0,
      nemesisId: 28,
    },
  },
  // Rancor Raiders
  {
    id: 22,
    name: "eze",
    team: "Batchers",
    team_id: 4,
    role: "Captain",
    stats: {
      impact: 82,
      flagCaptures: 8,
      flagReturns: 6,
      bcKills: 14,
      dbsKills: 6,
      dfaKills: 3,
      overallKills: 62,
      overallDeaths: 32,
      flagholdTime: 260,
      nemesisId: 15,
    },
  },
  {
    id: 23,
    name: "luke",
    team: "Batchers",
    team_id: 4,
    stats: {
      impact: 74,
      flagCaptures: 5,
      flagReturns: 4,
      bcKills: 10,
      dbsKills: 4,
      dfaKills: 2,
      overallKills: 46,
      overallDeaths: 28,
      flagholdTime: 195,
      nemesisId: 16,
    },
  },
  {
    id: 24,
    name: "downfall",
    team: "Batchers",
    team_id: 4,
    stats: {
      impact: 69,
      flagCaptures: 3,
      flagReturns: 5,
      bcKills: 8,
      dbsKills: 3,
      dfaKills: 1,
      overallKills: 34,
      overallDeaths: 26,
      flagholdTime: 155,
      nemesisId: 17,
    },
  },
  {
    id: 25,
    name: "dogsage",
    team: "Batchers",
    team_id: 4,
    stats: {
      impact: 61,
      flagCaptures: 2,
      flagReturns: 3,
      bcKills: 6,
      dbsKills: 2,
      dfaKills: 1,
      overallKills: 22,
      overallDeaths: 20,
      flagholdTime: 110,
      nemesisId: 18,
    },
  },
  {
    id: 26,
    name: "giraffe",
    team: "Batchers",
    team_id: 4,
    stats: {
      impact: 52,
      flagCaptures: 1,
      flagReturns: 1,
      bcKills: 4,
      dbsKills: 1,
      dfaKills: 0,
      overallKills: 12,
      overallDeaths: 16,
      flagholdTime: 75,
      nemesisId: 19,
    },
  },
  {
    id: 27,
    name: "Ferox",
    team: "Batchers",
    team_id: 4,
    stats: {
      impact: 40,
      flagCaptures: 0,
      flagReturns: 0,
      bcKills: 0,
      dbsKills: 0,
      dfaKills: 0,
      overallKills: 0,
      overallDeaths: 0,
      flagholdTime: 0,
      nemesisId: 20,
    },
  },
  {
    id: 28,
    name: "killzo",
    team: "Batchers",
    team_id: 4,
    stats: {
      impact: 40,
      flagCaptures: 0,
      flagReturns: 0,
      bcKills: 0,
      dbsKills: 0,
      dfaKills: 0,
      overallKills: 0,
      overallDeaths: 0,
      flagholdTime: 0,
      nemesisId: 21,
    },
  },
  // Sith Syndicate
  {
    id: 29,
    name: "goose",
    team: "d2dm",
    team_id: 5,
    role: "Captain",
    stats: {
      impact: 80,
      flagCaptures: 7,
      flagReturns: 5,
      bcKills: 12,
      dbsKills: 5,
      dfaKills: 2,
      overallKills: 56,
      overallDeaths: 30,
      flagholdTime: 240,
      nemesisId: 36,
    },
  },
  {
    id: 30,
    name: "ewok",
    team: "d2dm",
    team_id: 5,
    stats: {
      impact: 71,
      flagCaptures: 4,
      flagReturns: 3,
      bcKills: 9,
      dbsKills: 3,
      dfaKills: 1,
      overallKills: 42,
      overallDeaths: 26,
      flagholdTime: 180,
      nemesisId: 37,
    },
  },
  {
    id: 31,
    name: "Barney",
    team: "d2dm",
    team_id: 5,
    stats: {
      impact: 67,
      flagCaptures: 3,
      flagReturns: 4,
      bcKills: 7,
      dbsKills: 2,
      dfaKills: 1,
      overallKills: 30,
      overallDeaths: 24,
      flagholdTime: 140,
      nemesisId: 38,
    },
  },
  {
    id: 32,
    name: "yuki",
    team: "d2dm",
    team_id: 5,
    stats: {
      impact: 59,
      flagCaptures: 2,
      flagReturns: 2,
      bcKills: 5,
      dbsKills: 1,
      dfaKills: 0,
      overallKills: 18,
      overallDeaths: 18,
      flagholdTime: 95,
      nemesisId: 39,
    },
  },
  {
    id: 33,
    name: "devy",
    team: "d2dm",
    team_id: 5,
    stats: {
      impact: 50,
      flagCaptures: 1,
      flagReturns: 1,
      bcKills: 3,
      dbsKills: 1,
      dfaKills: 0,
      overallKills: 8,
      overallDeaths: 14,
      flagholdTime: 65,
      nemesisId: 40,
    },
  },
  {
    id: 34,
    name: "omerta",
    team: "d2dm",
    team_id: 5,
    stats: {
      impact: 40,
      flagCaptures: 0,
      flagReturns: 0,
      bcKills: 0,
      dbsKills: 0,
      dfaKills: 0,
      overallKills: 0,
      overallDeaths: 0,
      flagholdTime: 0,
      nemesisId: 41,
    },
  },
  {
    id: 35,
    name: "vee",
    team: "d2dm",
    team_id: 5,
    stats: {
      impact: 40,
      flagCaptures: 0,
      flagReturns: 0,
      bcKills: 0,
      dbsKills: 0,
      dfaKills: 0,
      overallKills: 0,
      overallDeaths: 0,
      flagholdTime: 0,
      nemesisId: 42,
    },
  },
  // Jedi Juggernauts
  {
    id: 36,
    name: "sora",
    team: "szok",
    team_id: 6,
    role: "Captain",
    stats: {
      impact: 78,
      flagCaptures: 6,
      flagReturns: 4,
      bcKills: 10,
      dbsKills: 4,
      dfaKills: 1,
      overallKills: 50,
      overallDeaths: 28,
      flagholdTime: 220,
      nemesisId: 29,
    },
  },
  {
    id: 37,
    name: "spacedghost",
    team: "szok",
    team_id: 6,
    stats: {
      impact: 70,
      flagCaptures: 3,
      flagReturns: 2,
      bcKills: 8,
      dbsKills: 2,
      dfaKills: 1,
      overallKills: 38,
      overallDeaths: 24,
      flagholdTime: 165,
      nemesisId: 30,
    },
  },
  {
    id: 38,
    name: "andon",
    team: "szok",
    team_id: 6,
    stats: {
      impact: 65,
      flagCaptures: 2,
      flagReturns: 3,
      bcKills: 6,
      dbsKills: 1,
      dfaKills: 0,
      overallKills: 26,
      overallDeaths: 22,
      flagholdTime: 125,
      nemesisId: 31,
    },
  },
  {
    id: 39,
    name: "matt",
    team: "szok",
    team_id: 6,
    stats: {
      impact: 57,
      flagCaptures: 1,
      flagReturns: 2,
      bcKills: 4,
      dbsKills: 1,
      dfaKills: 0,
      overallKills: 14,
      overallDeaths: 16,
      flagholdTime: 85,
      nemesisId: 32,
    },
  },
  {
    id: 40,
    name: "savior",
    team: "szok",
    team_id: 6,
    stats: {
      impact: 48,
      flagCaptures: 1,
      flagReturns: 1,
      bcKills: 2,
      dbsKills: 0,
      dfaKills: 0,
      overallKills: 4,
      overallDeaths: 12,
      flagholdTime: 55,
      nemesisId: 33,
    },
  },
  {
    id: 41,
    name: "apple",
    team: "szok",
    team_id: 6,
    stats: {
      impact: 40,
      flagCaptures: 0,
      flagReturns: 0,
      bcKills: 0,
      dbsKills: 0,
      dfaKills: 0,
      overallKills: 0,
      overallDeaths: 0,
      flagholdTime: 0,
      nemesisId: 34,
    },
  },
  {
    id: 42,
    name: "amor",
    team: "szok",
    team_id: 6,
    stats: {
      impact: 40,
      flagCaptures: 0,
      flagReturns: 0,
      bcKills: 0,
      dbsKills: 0,
      dfaKills: 0,
      overallKills: 0,
      overallDeaths: 0,
      flagholdTime: 0,
      nemesisId: 35,
    },
  },
  {
    id: 43,
    name: "bucky",
    team: "szok",
    team_id: 6,
    stats: {
      impact: 40,
      flagCaptures: 0,
      flagReturns: 0,
      bcKills: 0,
      dbsKills: 0,
      dfaKills: 0,
      overallKills: 0,
      overallDeaths: 0,
      flagholdTime: 0,
      nemesisId: 1,
    },
  },
]

// Match history data - renamed from matchHistory to matches
export const matches = [
  {
    id: 1,
    round: "Group Stage",
    teamA: "93 Octane",
    teamB: "Crash squad",
    scoreA: 7,
    scoreB: 5,
    date: "2023-10-15",
    teamAReturns: 12,
    teamBReturns: 10,
    teamAKills: 45,
    teamBKills: 42,
    teamAFlagTime: 420,
    teamBFlagTime: 380,
  },
  {
    id: 2,
    round: "Group Stage",
    teamA: "rTr",
    teamB: "Batchers",
    scoreA: 6,
    scoreB: 4,
    date: "2023-10-16",
    teamAReturns: 8,
    teamBReturns: 6,
    teamAKills: 38,
    teamBKills: 32,
    teamAFlagTime: 350,
    teamBFlagTime: 290,
  },
  {
    id: 3,
    round: "Group Stage",
    teamA: "d2dm",
    teamB: "szok",
    scoreA: 5,
    scoreB: 3,
    date: "2023-10-17",
    teamAReturns: 7,
    teamBReturns: 5,
    teamAKills: 30,
    teamBKills: 25,
    teamAFlagTime: 280,
    teamBFlagTime: 220,
  },
  {
    id: 4,
    round: "Group Stage",
    teamA: "93 Octane",
    teamB: "rTr",
    scoreA: 7,
    scoreB: 3,
    date: "2023-10-18",
    teamAReturns: 10,
    teamBReturns: 6,
    teamAKills: 42,
    teamBKills: 28,
    teamAFlagTime: 390,
    teamBFlagTime: 240,
  },
  {
    id: 5,
    round: "Group Stage",
    teamA: "Crash squad",
    teamB: "d2dm",
    scoreA: 6,
    scoreB: 2,
    date: "2023-10-19",
    teamAReturns: 9,
    teamBReturns: 4,
    teamAKills: 40,
    teamBKills: 22,
    teamAFlagTime: 370,
    teamBFlagTime: 180,
  },
  {
    id: 6,
    round: "Group Stage",
    teamA: "Batchers",
    teamB: "szok",
    scoreA: 5,
    scoreB: 5,
    date: "2023-10-20",
    teamAReturns: 8,
    teamBReturns: 8,
    teamAKills: 35,
    teamBKills: 35,
    teamAFlagTime: 320,
    teamBFlagTime: 320,
  },
  {
    id: 7,
    round: "Group Stage",
    teamA: "93 Octane",
    teamB: "d2dm",
    scoreA: 7,
    scoreB: 2,
    date: "2023-10-21",
    teamAReturns: 11,
    teamBReturns: 3,
    teamAKills: 44,
    teamBKills: 20,
    teamAFlagTime: 410,
    teamBFlagTime: 170,
  },
  {
    id: 8,
    round: "Group Stage",
    teamA: "Crash squad",
    teamB: "Batchers",
    scoreA: 6,
    scoreB: 3,
    date: "2023-10-22",
    teamAReturns: 10,
    teamBReturns: 5,
    teamAKills: 42,
    teamBKills: 26,
    teamAFlagTime: 380,
    teamBFlagTime: 210,
  },
  {
    id: 9,
    round: "Group Stage",
    teamA: "rTr",
    teamB: "szok",
    scoreA: 7,
    scoreB: 2,
    date: "2023-10-23",
    teamAReturns: 9,
    teamBReturns: 3,
    teamAKills: 38,
    teamBKills: 18,
    teamAFlagTime: 360,
    teamBFlagTime: 160,
  },
  {
    id: 10,
    round: "Semifinal",
    teamA: "93 Octane",
    teamB: "rTr",
    scoreA: 7,
    scoreB: 4,
    date: "2023-10-28",
    teamAReturns: 12,
    teamBReturns: 7,
    teamAKills: 48,
    teamBKills: 32,
    teamAFlagTime: 430,
    teamBFlagTime: 260,
  },
]

// For backward compatibility
export const matchHistory = matches

// Upcoming matches data - renamed from upcomingMatches to fixtures
export const fixtures = [
  {
    id: 11,
    round: "Semifinal",
    teamA: "Crash squad",
    teamB: "Batchers",
    date: "2023-10-29",
    time: "19:00",
  },
  {
    id: 12,
    round: "3rd Place Match",
    teamA: "rTr",
    teamB: "d2dm",
    date: "2023-11-04",
    time: "17:00",
  },
  {
    id: 13,
    round: "Final",
    teamA: "93 Octane",
    teamB: "Crash squad",
    date: "2023-11-05",
    time: "19:00",
  },
]

// For backward compatibility
export const upcomingMatches = fixtures
