import type {
  TeamWithStatsAndPlayers,
  PlayerWithStatsAndTeamName,
  MatchWithTeamNames,
} from "./data-service";

// --- Static Data --- //
// NOTE: This data needs to match the interfaces defined in data-service.ts
// for the static fallback to work correctly and be type-safe.

// TEAM DATA
const staticTeamData: Omit<
  TeamWithStatsAndPlayers,
  "created_at" | "updated_at"
>[] = [
  {
    id: 1,
    name: "93 Octane",
    founded: "2023",
    team_stats: {
      id: 1, // Assuming stats ID matches team ID for simplicity
      team_id: 1,
      matches_played: 8,
      matches_won: 6,
      matches_drawn: 1,
      matches_lost: 1,
      captures: 32,
      flag_returns: 28,
      kills: 245,
      points: 19,
      created_at: null,
      updated_at: null,
    },
    players_list: [
      // Populated from players data below
      { id: 1, name: "bizzle" },
      { id: 2, name: "fetchd" },
      { id: 3, name: "shax" },
      { id: 4, name: "andrew" },
      { id: 5, name: "interlude" },
      { id: 6, name: "loom" },
      { id: 7, name: "ultra" },
    ],
  },
  {
    id: 2,
    name: "Crash squad",
    founded: "2023",
    team_stats: {
      id: 2,
      team_id: 2,
      matches_played: 8,
      matches_won: 5,
      matches_drawn: 2,
      matches_lost: 1,
      captures: 29,
      flag_returns: 31,
      kills: 267,
      points: 17,
      created_at: null,
      updated_at: null,
    },
    players_list: [
      { id: 8, name: "cooky" },
      { id: 9, name: "arhont" },
      { id: 10, name: "dreamwise" },
      { id: 11, name: "cheese" },
      { id: 12, name: "original" },
      { id: 13, name: "phoenix" },
      { id: 14, name: "jin" },
    ],
  },
  {
    id: 3,
    name: "rTr",
    founded: "2023",
    team_stats: {
      id: 3,
      team_id: 3,
      matches_played: 8,
      matches_won: 4,
      matches_drawn: 1,
      matches_lost: 3,
      captures: 24,
      flag_returns: 22,
      kills: 198,
      points: 13,
      created_at: null,
      updated_at: null,
    },
    players_list: [
      { id: 15, name: "suvix" },
      { id: 16, name: "millhouse" },
      { id: 17, name: "xan" },
      { id: 18, name: "phenom" },
      { id: 19, name: "plasma" },
      { id: 20, name: "flawless" },
      { id: 21, name: "levi" },
    ],
  },
  {
    id: 4,
    name: "Batchers",
    founded: "2023",
    team_stats: {
      id: 4,
      team_id: 4,
      matches_played: 8,
      matches_won: 3,
      matches_drawn: 2,
      matches_lost: 3,
      captures: 21,
      flag_returns: 19,
      kills: 176,
      points: 11,
      created_at: null,
      updated_at: null,
    },
    players_list: [
      { id: 22, name: "eze" },
      { id: 23, name: "luke" },
      { id: 24, name: "downfall" },
      { id: 25, name: "dogsage" },
      { id: 26, name: "giraffe" },
      { id: 27, name: "Ferox" },
      { id: 28, name: "killzo" },
    ],
  },
  {
    id: 5,
    name: "d2dm",
    founded: "2023",
    team_stats: {
      id: 5,
      team_id: 5,
      matches_played: 8,
      matches_won: 2,
      matches_drawn: 1,
      matches_lost: 5,
      captures: 18,
      flag_returns: 16,
      kills: 154,
      points: 7,
      created_at: null,
      updated_at: null,
    },
    players_list: [
      { id: 29, name: "goose" },
      { id: 30, name: "ewok" },
      { id: 31, name: "Barney" },
      { id: 32, name: "yuki" },
      { id: 33, name: "devy" },
      { id: 34, name: "omerta" },
      { id: 35, name: "vee" },
    ],
  },
  {
    id: 6,
    name: "szok",
    founded: "2023",
    team_stats: {
      id: 6,
      team_id: 6,
      matches_played: 8,
      matches_won: 1,
      matches_drawn: 1,
      matches_lost: 6,
      captures: 14,
      flag_returns: 12,
      kills: 132,
      points: 4,
      created_at: null,
      updated_at: null,
    },
    players_list: [
      { id: 36, name: "sora" },
      { id: 37, name: "spacedghost" },
      { id: 38, name: "andon" },
      { id: 39, name: "matt" },
      { id: 40, name: "savior" },
      { id: 41, name: "apple" },
      { id: 42, name: "amor" },
      { id: 43, name: "bucky" },
    ],
  },
];

// Augment with timestamps if needed, or handle potential nulls in components
export const teams: TeamWithStatsAndPlayers[] = staticTeamData.map((team) => ({
  ...team,
  created_at: null,
  updated_at: null,
}));

// PLAYER DATA
const staticPlayerData: Omit<
  PlayerWithStatsAndTeamName,
  "created_at" | "updated_at"
>[] = [
  // Team 1: 93 Octane
  {
    id: 1,
    name: "bizzle",
    team_id: 1,
    role: "Captain",
    team_name: "93 Octane",
    player_stats: {
      id: 1,
      player_id: 1,
      impact: 92,
      flag_captures: 12,
      flag_returns: 10,
      bc_kills: 15,
      dbs_kills: 8,
      dfa_kills: 5,
      overall_kills: 78,
      overall_deaths: 32,
      flaghold_time: 345,
      created_at: null,
      updated_at: null,
    },
  },
  {
    id: 2,
    name: "fetchd",
    team_id: 1,
    role: null,
    team_name: "93 Octane",
    player_stats: {
      id: 2,
      player_id: 2,
      impact: 88,
      flag_captures: 8,
      flag_returns: 12,
      bc_kills: 12,
      dbs_kills: 10,
      dfa_kills: 3,
      overall_kills: 65,
      overall_deaths: 28,
      flaghold_time: 278,
      created_at: null,
      updated_at: null,
    },
  },
  {
    id: 3,
    name: "shax",
    team_id: 1,
    role: null,
    team_name: "93 Octane",
    player_stats: {
      id: 3,
      player_id: 3,
      impact: 75,
      flag_captures: 6,
      flag_returns: 4,
      bc_kills: 8,
      dbs_kills: 6,
      dfa_kills: 2,
      overall_kills: 42,
      overall_deaths: 35,
      flaghold_time: 198,
      created_at: null,
      updated_at: null,
    },
  },
  {
    id: 4,
    name: "andrew",
    team_id: 1,
    role: null,
    team_name: "93 Octane",
    player_stats: {
      id: 4,
      player_id: 4,
      impact: 70,
      flag_captures: 4,
      flag_returns: 2,
      bc_kills: 10,
      dbs_kills: 4,
      dfa_kills: 6,
      overall_kills: 38,
      overall_deaths: 30,
      flaghold_time: 156,
      created_at: null,
      updated_at: null,
    },
  },
  {
    id: 5,
    name: "interlude",
    team_id: 1,
    role: null,
    team_name: "93 Octane",
    player_stats: {
      id: 5,
      player_id: 5,
      impact: 58,
      flag_captures: 2,
      flag_returns: 0,
      bc_kills: 5,
      dbs_kills: 2,
      dfa_kills: 1,
      overall_kills: 22,
      overall_deaths: 18,
      flaghold_time: 87,
      created_at: null,
      updated_at: null,
    },
  },
  {
    id: 6,
    name: "loom",
    team_id: 1,
    role: null,
    team_name: "93 Octane",
    player_stats: {
      id: 6,
      player_id: 6,
      impact: 40,
      flag_captures: 0,
      flag_returns: 0,
      bc_kills: 0,
      dbs_kills: 0,
      dfa_kills: 0,
      overall_kills: 0,
      overall_deaths: 0,
      flaghold_time: 0,
      created_at: null,
      updated_at: null,
    },
  },
  {
    id: 7,
    name: "ultra",
    team_id: 1,
    role: null,
    team_name: "93 Octane",
    player_stats: {
      id: 7,
      player_id: 7,
      impact: 40,
      flag_captures: 0,
      flag_returns: 0,
      bc_kills: 0,
      dbs_kills: 0,
      dfa_kills: 0,
      overall_kills: 0,
      overall_deaths: 0,
      flaghold_time: 0,
      created_at: null,
      updated_at: null,
    },
  },
  // Team 2: Crash squad
  {
    id: 8,
    name: "cooky",
    team_id: 2,
    role: "Captain",
    team_name: "Crash squad",
    player_stats: {
      id: 8,
      player_id: 8,
      impact: 90,
      flag_captures: 10,
      flag_returns: 8,
      bc_kills: 18,
      dbs_kills: 12,
      dfa_kills: 7,
      overall_kills: 85,
      overall_deaths: 30,
      flaghold_time: 320,
      created_at: null,
      updated_at: null,
    },
  },
  {
    id: 9,
    name: "arhont",
    team_id: 2,
    role: null,
    team_name: "Crash squad",
    player_stats: {
      id: 9,
      player_id: 9,
      impact: 87,
      flag_captures: 9,
      flag_returns: 11,
      bc_kills: 14,
      dbs_kills: 9,
      dfa_kills: 8,
      overall_kills: 72,
      overall_deaths: 35,
      flaghold_time: 290,
      created_at: null,
      updated_at: null,
    },
  },
  {
    id: 10,
    name: "dreamwise",
    team_id: 2,
    role: null,
    team_name: "Crash squad",
    player_stats: {
      id: 10,
      player_id: 10,
      impact: 76,
      flag_captures: 5,
      flag_returns: 7,
      bc_kills: 10,
      dbs_kills: 5,
      dfa_kills: 4,
      overall_kills: 48,
      overall_deaths: 32,
      flaghold_time: 210,
      created_at: null,
      updated_at: null,
    },
  },
  {
    id: 11,
    name: "cheese",
    team_id: 2,
    role: null,
    team_name: "Crash squad",
    player_stats: {
      id: 11,
      player_id: 11,
      impact: 68,
      flag_captures: 3,
      flag_returns: 4,
      bc_kills: 8,
      dbs_kills: 3,
      dfa_kills: 2,
      overall_kills: 36,
      overall_deaths: 28,
      flaghold_time: 145,
      created_at: null,
      updated_at: null,
    },
  },
  {
    id: 12,
    name: "original",
    team_id: 2,
    role: null,
    team_name: "Crash squad",
    player_stats: {
      id: 12,
      player_id: 12,
      impact: 60,
      flag_captures: 2,
      flag_returns: 1,
      bc_kills: 6,
      dbs_kills: 2,
      dfa_kills: 1,
      overall_kills: 26,
      overall_deaths: 22,
      flaghold_time: 98,
      created_at: null,
      updated_at: null,
    },
  },
  {
    id: 13,
    name: "phoenix",
    team_id: 2,
    role: null,
    team_name: "Crash squad",
    player_stats: {
      id: 13,
      player_id: 13,
      impact: 40,
      flag_captures: 0,
      flag_returns: 0,
      bc_kills: 0,
      dbs_kills: 0,
      dfa_kills: 0,
      overall_kills: 0,
      overall_deaths: 0,
      flaghold_time: 0,
      created_at: null,
      updated_at: null,
    },
  },
  {
    id: 14,
    name: "jin",
    team_id: 2,
    role: null,
    team_name: "Crash squad",
    player_stats: {
      id: 14,
      player_id: 14,
      impact: 40,
      flag_captures: 0,
      flag_returns: 0,
      bc_kills: 0,
      dbs_kills: 0,
      dfa_kills: 0,
      overall_kills: 0,
      overall_deaths: 0,
      flaghold_time: 0,
      created_at: null,
      updated_at: null,
    },
  },
  // Team 3: rTr
  {
    id: 15,
    name: "suvix",
    team_id: 3,
    role: "Captain",
    team_name: "rTr",
    player_stats: {
      id: 15,
      player_id: 15,
      impact: 85,
      flag_captures: 9,
      flag_returns: 7,
      bc_kills: 16,
      dbs_kills: 7,
      dfa_kills: 4,
      overall_kills: 68,
      overall_deaths: 34,
      flaghold_time: 280,
      created_at: null,
      updated_at: null,
    },
  },
  {
    id: 16,
    name: "millhouse",
    team_id: 3,
    role: null,
    team_name: "rTr",
    player_stats: {
      id: 16,
      player_id: 16,
      impact: 78,
      flag_captures: 6,
      flag_returns: 5,
      bc_kills: 12,
      dbs_kills: 5,
      dfa_kills: 3,
      overall_kills: 52,
      overall_deaths: 30,
      flaghold_time: 215,
      created_at: null,
      updated_at: null,
    },
  },
  {
    id: 17,
    name: "xan",
    team_id: 3,
    role: null,
    team_name: "rTr",
    player_stats: {
      id: 17,
      player_id: 17,
      impact: 72,
      flag_captures: 4,
      flag_returns: 6,
      bc_kills: 9,
      dbs_kills: 4,
      dfa_kills: 2,
      overall_kills: 38,
      overall_deaths: 28,
      flaghold_time: 175,
      created_at: null,
      updated_at: null,
    },
  },
  {
    id: 18,
    name: "phenom",
    team_id: 3,
    role: null,
    team_name: "rTr",
    player_stats: {
      id: 18,
      player_id: 18,
      impact: 63,
      flag_captures: 3,
      flag_returns: 2,
      bc_kills: 7,
      dbs_kills: 3,
      dfa_kills: 1,
      overall_kills: 24,
      overall_deaths: 22,
      flaghold_time: 120,
      created_at: null,
      updated_at: null,
    },
  },
  {
    id: 19,
    name: "plasma",
    team_id: 3,
    role: null,
    team_name: "rTr",
    player_stats: {
      id: 19,
      player_id: 19,
      impact: 55,
      flag_captures: 2,
      flag_returns: 2,
      bc_kills: 5,
      dbs_kills: 2,
      dfa_kills: 1,
      overall_kills: 16,
      overall_deaths: 18,
      flaghold_time: 85,
      created_at: null,
      updated_at: null,
    },
  },
  {
    id: 20,
    name: "flawless",
    team_id: 3,
    role: null,
    team_name: "rTr",
    player_stats: {
      id: 20,
      player_id: 20,
      impact: 40,
      flag_captures: 0,
      flag_returns: 0,
      bc_kills: 0,
      dbs_kills: 0,
      dfa_kills: 0,
      overall_kills: 0,
      overall_deaths: 0,
      flaghold_time: 0,
      created_at: null,
      updated_at: null,
    },
  },
  {
    id: 21,
    name: "levi",
    team_id: 3,
    role: null,
    team_name: "rTr",
    player_stats: {
      id: 21,
      player_id: 21,
      impact: 40,
      flag_captures: 0,
      flag_returns: 0,
      bc_kills: 0,
      dbs_kills: 0,
      dfa_kills: 0,
      overall_kills: 0,
      overall_deaths: 0,
      flaghold_time: 0,
      created_at: null,
      updated_at: null,
    },
  },
  // Team 4: Batchers
  {
    id: 22,
    name: "eze",
    team_id: 4,
    role: "Captain",
    team_name: "Batchers",
    player_stats: {
      id: 22,
      player_id: 22,
      impact: 82,
      flag_captures: 8,
      flag_returns: 6,
      bc_kills: 14,
      dbs_kills: 6,
      dfa_kills: 3,
      overall_kills: 62,
      overall_deaths: 32,
      flaghold_time: 260,
      created_at: null,
      updated_at: null,
    },
  },
  {
    id: 23,
    name: "luke",
    team_id: 4,
    role: null,
    team_name: "Batchers",
    player_stats: {
      id: 23,
      player_id: 23,
      impact: 74,
      flag_captures: 5,
      flag_returns: 4,
      bc_kills: 10,
      dbs_kills: 4,
      dfa_kills: 2,
      overall_kills: 46,
      overall_deaths: 28,
      flaghold_time: 195,
      created_at: null,
      updated_at: null,
    },
  },
  {
    id: 24,
    name: "downfall",
    team_id: 4,
    role: null,
    team_name: "Batchers",
    player_stats: {
      id: 24,
      player_id: 24,
      impact: 69,
      flag_captures: 3,
      flag_returns: 5,
      bc_kills: 8,
      dbs_kills: 3,
      dfa_kills: 1,
      overall_kills: 34,
      overall_deaths: 26,
      flaghold_time: 155,
      created_at: null,
      updated_at: null,
    },
  },
  {
    id: 25,
    name: "dogsage",
    team_id: 4,
    role: null,
    team_name: "Batchers",
    player_stats: {
      id: 25,
      player_id: 25,
      impact: 61,
      flag_captures: 2,
      flag_returns: 3,
      bc_kills: 6,
      dbs_kills: 2,
      dfa_kills: 1,
      overall_kills: 22,
      overall_deaths: 20,
      flaghold_time: 110,
      created_at: null,
      updated_at: null,
    },
  },
  {
    id: 26,
    name: "giraffe",
    team_id: 4,
    role: null,
    team_name: "Batchers",
    player_stats: {
      id: 26,
      player_id: 26,
      impact: 52,
      flag_captures: 1,
      flag_returns: 1,
      bc_kills: 4,
      dbs_kills: 1,
      dfa_kills: 0,
      overall_kills: 12,
      overall_deaths: 16,
      flaghold_time: 75,
      created_at: null,
      updated_at: null,
    },
  },
  {
    id: 27,
    name: "Ferox",
    team_id: 4,
    role: null,
    team_name: "Batchers",
    player_stats: {
      id: 27,
      player_id: 27,
      impact: 40,
      flag_captures: 0,
      flag_returns: 0,
      bc_kills: 0,
      dbs_kills: 0,
      dfa_kills: 0,
      overall_kills: 0,
      overall_deaths: 0,
      flaghold_time: 0,
      created_at: null,
      updated_at: null,
    },
  },
  {
    id: 28,
    name: "killzo",
    team_id: 4,
    role: null,
    team_name: "Batchers",
    player_stats: {
      id: 28,
      player_id: 28,
      impact: 40,
      flag_captures: 0,
      flag_returns: 0,
      bc_kills: 0,
      dbs_kills: 0,
      dfa_kills: 0,
      overall_kills: 0,
      overall_deaths: 0,
      flaghold_time: 0,
      created_at: null,
      updated_at: null,
    },
  },
  // Team 5: d2dm
  {
    id: 29,
    name: "goose",
    team_id: 5,
    role: "Captain",
    team_name: "d2dm",
    player_stats: {
      id: 29,
      player_id: 29,
      impact: 80,
      flag_captures: 7,
      flag_returns: 5,
      bc_kills: 12,
      dbs_kills: 5,
      dfa_kills: 2,
      overall_kills: 56,
      overall_deaths: 30,
      flaghold_time: 240,
      created_at: null,
      updated_at: null,
    },
  },
  {
    id: 30,
    name: "ewok",
    team_id: 5,
    role: null,
    team_name: "d2dm",
    player_stats: {
      id: 30,
      player_id: 30,
      impact: 71,
      flag_captures: 4,
      flag_returns: 3,
      bc_kills: 9,
      dbs_kills: 3,
      dfa_kills: 1,
      overall_kills: 42,
      overall_deaths: 26,
      flaghold_time: 180,
      created_at: null,
      updated_at: null,
    },
  },
  {
    id: 31,
    name: "Barney",
    team_id: 5,
    role: null,
    team_name: "d2dm",
    player_stats: {
      id: 31,
      player_id: 31,
      impact: 67,
      flag_captures: 3,
      flag_returns: 4,
      bc_kills: 7,
      dbs_kills: 2,
      dfa_kills: 1,
      overall_kills: 30,
      overall_deaths: 24,
      flaghold_time: 140,
      created_at: null,
      updated_at: null,
    },
  },
  {
    id: 32,
    name: "yuki",
    team_id: 5,
    role: null,
    team_name: "d2dm",
    player_stats: {
      id: 32,
      player_id: 32,
      impact: 59,
      flag_captures: 2,
      flag_returns: 2,
      bc_kills: 5,
      dbs_kills: 1,
      dfa_kills: 0,
      overall_kills: 18,
      overall_deaths: 18,
      flaghold_time: 95,
      created_at: null,
      updated_at: null,
    },
  },
  {
    id: 33,
    name: "devy",
    team_id: 5,
    role: null,
    team_name: "d2dm",
    player_stats: {
      id: 33,
      player_id: 33,
      impact: 50,
      flag_captures: 1,
      flag_returns: 1,
      bc_kills: 3,
      dbs_kills: 1,
      dfa_kills: 0,
      overall_kills: 8,
      overall_deaths: 14,
      flaghold_time: 65,
      created_at: null,
      updated_at: null,
    },
  },
  {
    id: 34,
    name: "omerta",
    team_id: 5,
    role: null,
    team_name: "d2dm",
    player_stats: {
      id: 34,
      player_id: 34,
      impact: 40,
      flag_captures: 0,
      flag_returns: 0,
      bc_kills: 0,
      dbs_kills: 0,
      dfa_kills: 0,
      overall_kills: 0,
      overall_deaths: 0,
      flaghold_time: 0,
      created_at: null,
      updated_at: null,
    },
  },
  {
    id: 35,
    name: "vee",
    team_id: 5,
    role: null,
    team_name: "d2dm",
    player_stats: {
      id: 35,
      player_id: 35,
      impact: 40,
      flag_captures: 0,
      flag_returns: 0,
      bc_kills: 0,
      dbs_kills: 0,
      dfa_kills: 0,
      overall_kills: 0,
      overall_deaths: 0,
      flaghold_time: 0,
      created_at: null,
      updated_at: null,
    },
  },
  // Team 6: szok
  {
    id: 36,
    name: "sora",
    team_id: 6,
    role: "Captain",
    team_name: "szok",
    player_stats: {
      id: 36,
      player_id: 36,
      impact: 78,
      flag_captures: 6,
      flag_returns: 4,
      bc_kills: 10,
      dbs_kills: 4,
      dfa_kills: 1,
      overall_kills: 50,
      overall_deaths: 28,
      flaghold_time: 220,
      created_at: null,
      updated_at: null,
    },
  },
  {
    id: 37,
    name: "spacedghost",
    team_id: 6,
    role: null,
    team_name: "szok",
    player_stats: {
      id: 37,
      player_id: 37,
      impact: 70,
      flag_captures: 3,
      flag_returns: 2,
      bc_kills: 8,
      dbs_kills: 2,
      dfa_kills: 1,
      overall_kills: 38,
      overall_deaths: 24,
      flaghold_time: 165,
      created_at: null,
      updated_at: null,
    },
  },
  {
    id: 38,
    name: "andon",
    team_id: 6,
    role: null,
    team_name: "szok",
    player_stats: {
      id: 38,
      player_id: 38,
      impact: 65,
      flag_captures: 2,
      flag_returns: 3,
      bc_kills: 6,
      dbs_kills: 1,
      dfa_kills: 0,
      overall_kills: 26,
      overall_deaths: 22,
      flaghold_time: 125,
      created_at: null,
      updated_at: null,
    },
  },
  {
    id: 39,
    name: "matt",
    team_id: 6,
    role: null,
    team_name: "szok",
    player_stats: {
      id: 39,
      player_id: 39,
      impact: 57,
      flag_captures: 1,
      flag_returns: 2,
      bc_kills: 4,
      dbs_kills: 1,
      dfa_kills: 0,
      overall_kills: 14,
      overall_deaths: 16,
      flaghold_time: 85,
      created_at: null,
      updated_at: null,
    },
  },
  {
    id: 40,
    name: "savior",
    team_id: 6,
    role: null,
    team_name: "szok",
    player_stats: {
      id: 40,
      player_id: 40,
      impact: 48,
      flag_captures: 1,
      flag_returns: 1,
      bc_kills: 2,
      dbs_kills: 0,
      dfa_kills: 0,
      overall_kills: 4,
      overall_deaths: 12,
      flaghold_time: 55,
      created_at: null,
      updated_at: null,
    },
  },
  {
    id: 41,
    name: "apple",
    team_id: 6,
    role: null,
    team_name: "szok",
    player_stats: {
      id: 41,
      player_id: 41,
      impact: 40,
      flag_captures: 0,
      flag_returns: 0,
      bc_kills: 0,
      dbs_kills: 0,
      dfa_kills: 0,
      overall_kills: 0,
      overall_deaths: 0,
      flaghold_time: 0,
      created_at: null,
      updated_at: null,
    },
  },
  {
    id: 42,
    name: "amor",
    team_id: 6,
    role: null,
    team_name: "szok",
    player_stats: {
      id: 42,
      player_id: 42,
      impact: 40,
      flag_captures: 0,
      flag_returns: 0,
      bc_kills: 0,
      dbs_kills: 0,
      dfa_kills: 0,
      overall_kills: 0,
      overall_deaths: 0,
      flaghold_time: 0,
      created_at: null,
      updated_at: null,
    },
  },
  {
    id: 43,
    name: "bucky",
    team_id: 6,
    role: null,
    team_name: "szok",
    player_stats: {
      id: 43,
      player_id: 43,
      impact: 40,
      flag_captures: 0,
      flag_returns: 0,
      bc_kills: 0,
      dbs_kills: 0,
      dfa_kills: 0,
      overall_kills: 0,
      overall_deaths: 0,
      flaghold_time: 0,
      created_at: null,
      updated_at: null,
    },
  },
];

export const players: PlayerWithStatsAndTeamName[] = staticPlayerData.map(
  (player) => ({
    ...player,
    created_at: null,
    updated_at: null,
  })
);

// MATCH HISTORY DATA
const staticMatchHistoryData: Omit<
  MatchWithTeamNames,
  "created_at" | "updated_at"
>[] = [
  {
    id: 1,
    round: "Group Stage",
    team_a_id: 1,
    team_b_id: 2,
    team_a_name: "93 Octane",
    team_b_name: "Crash squad",
    score_a: 7,
    score_b: 5,
    date: "2023-10-15",
    time: null,
    team_a_returns: 12,
    team_b_returns: 10,
    team_a_kills: 45,
    team_b_kills: 42,
    team_a_flag_time: 420,
    team_b_flag_time: 380,
    is_completed: true,
  },
  {
    id: 2,
    round: "Group Stage",
    team_a_id: 3,
    team_b_id: 4,
    team_a_name: "rTr",
    team_b_name: "Batchers",
    score_a: 6,
    score_b: 4,
    date: "2023-10-16",
    time: null,
    team_a_returns: 8,
    team_b_returns: 6,
    team_a_kills: 38,
    team_b_kills: 32,
    team_a_flag_time: 350,
    team_b_flag_time: 290,
    is_completed: true,
  },
  {
    id: 3,
    round: "Group Stage",
    team_a_id: 5,
    team_b_id: 6,
    team_a_name: "d2dm",
    team_b_name: "szok",
    score_a: 5,
    score_b: 3,
    date: "2023-10-17",
    time: null,
    team_a_returns: 7,
    team_b_returns: 5,
    team_a_kills: 30,
    team_b_kills: 25,
    team_a_flag_time: 280,
    team_b_flag_time: 220,
    is_completed: true,
  },
  {
    id: 4,
    round: "Group Stage",
    team_a_id: 1,
    team_b_id: 3,
    team_a_name: "93 Octane",
    team_b_name: "rTr",
    score_a: 7,
    score_b: 3,
    date: "2023-10-18",
    time: null,
    team_a_returns: 10,
    team_b_returns: 6,
    team_a_kills: 42,
    team_b_kills: 28,
    team_a_flag_time: 390,
    team_b_flag_time: 240,
    is_completed: true,
  },
  {
    id: 5,
    round: "Group Stage",
    team_a_id: 2,
    team_b_id: 5,
    team_a_name: "Crash squad",
    team_b_name: "d2dm",
    score_a: 6,
    score_b: 2,
    date: "2023-10-19",
    time: null,
    team_a_returns: 9,
    team_b_returns: 4,
    team_a_kills: 40,
    team_b_kills: 22,
    team_a_flag_time: 370,
    team_b_flag_time: 180,
    is_completed: true,
  },
  {
    id: 6,
    round: "Group Stage",
    team_a_id: 4,
    team_b_id: 6,
    team_a_name: "Batchers",
    team_b_name: "szok",
    score_a: 5,
    score_b: 5,
    date: "2023-10-20",
    time: null,
    team_a_returns: 8,
    team_b_returns: 8,
    team_a_kills: 35,
    team_b_kills: 35,
    team_a_flag_time: 320,
    team_b_flag_time: 320,
    is_completed: true,
  },
  {
    id: 7,
    round: "Group Stage",
    team_a_id: 1,
    team_b_id: 5,
    team_a_name: "93 Octane",
    team_b_name: "d2dm",
    score_a: 7,
    score_b: 2,
    date: "2023-10-21",
    time: null,
    team_a_returns: 11,
    team_b_returns: 3,
    team_a_kills: 44,
    team_b_kills: 20,
    team_a_flag_time: 410,
    team_b_flag_time: 170,
    is_completed: true,
  },
  {
    id: 8,
    round: "Group Stage",
    team_a_id: 2,
    team_b_id: 4,
    team_a_name: "Crash squad",
    team_b_name: "Batchers",
    score_a: 6,
    score_b: 3,
    date: "2023-10-22",
    time: null,
    team_a_returns: 10,
    team_b_returns: 5,
    team_a_kills: 42,
    team_b_kills: 26,
    team_a_flag_time: 380,
    team_b_flag_time: 210,
    is_completed: true,
  },
  {
    id: 9,
    round: "Group Stage",
    team_a_id: 3,
    team_b_id: 6,
    team_a_name: "rTr",
    team_b_name: "szok",
    score_a: 7,
    score_b: 2,
    date: "2023-10-23",
    time: null,
    team_a_returns: 9,
    team_b_returns: 3,
    team_a_kills: 38,
    team_b_kills: 18,
    team_a_flag_time: 360,
    team_b_flag_time: 160,
    is_completed: true,
  },
  {
    id: 10,
    round: "Semifinal",
    team_a_id: 1,
    team_b_id: 3,
    team_a_name: "93 Octane",
    team_b_name: "rTr",
    score_a: 7,
    score_b: 4,
    date: "2023-10-28",
    time: null,
    team_a_returns: 12,
    team_b_returns: 7,
    team_a_kills: 48,
    team_b_kills: 32,
    team_a_flag_time: 430,
    team_b_flag_time: 260,
    is_completed: true,
  },
];

export const matchHistory: MatchWithTeamNames[] = staticMatchHistoryData.map(
  (match) => ({
    ...match,
    created_at: null,
    updated_at: null,
  })
);

// UPCOMING MATCHES DATA
const staticUpcomingData: Omit<
  MatchWithTeamNames,
  "created_at" | "updated_at"
>[] = [
  {
    id: 11,
    round: "Semifinal",
    team_a_id: 2,
    team_b_id: 4,
    team_a_name: "Crash squad",
    team_b_name: "Batchers",
    date: "2023-10-29",
    time: "19:00",
    score_a: null,
    score_b: null,
    team_a_returns: null,
    team_b_returns: null,
    team_a_kills: null,
    team_b_kills: null,
    team_a_flag_time: null,
    team_b_flag_time: null,
    is_completed: false,
  },
  {
    id: 12,
    round: "3rd Place Match",
    team_a_id: 3,
    team_b_id: 5,
    team_a_name: "rTr",
    team_b_name: "d2dm",
    date: "2023-11-04",
    time: "17:00",
    score_a: null,
    score_b: null,
    team_a_returns: null,
    team_b_returns: null,
    team_a_kills: null,
    team_b_kills: null,
    team_a_flag_time: null,
    team_b_flag_time: null,
    is_completed: false,
  },
  {
    id: 13,
    round: "Final",
    team_a_id: 1,
    team_b_id: 2,
    team_a_name: "93 Octane",
    team_b_name: "Crash squad",
    date: "2023-11-05",
    time: "19:00",
    score_a: null,
    score_b: null,
    team_a_returns: null,
    team_b_returns: null,
    team_a_kills: null,
    team_b_kills: null,
    team_a_flag_time: null,
    team_b_flag_time: null,
    is_completed: false,
  },
];

export const upcomingMatches: MatchWithTeamNames[] = staticUpcomingData.map(
  (match) => ({
    ...match,
    created_at: null,
    updated_at: null,
  })
);

// Remove backward compatibility exports if they exist
// export const matches = ... (if it existed separate from matchHistory)
// export const fixtures = ... (if it existed separate from upcomingMatches)
